* Introduction
  The functions usable wrapped from main are tested and documented
* run
  The main function with name changed
** do_error
   Since the original do_error used exit(1), which is unacceptable for python calling. So I modify it to return to the main function, and add
   #+BEGIN_SRC c
   return 1;
   #+END_SRC
   Just after returning from do_error
* Documentation
  - Usage of Graphplan
    #+BEGIN_SRC python
    >>> import graphplan
    >>> argv = ['graphplan', '-o', 'domain.pddl', '-f', 'problem.pddl']
    >>> graphplan.run(argv)
    #+END_SRC
 
  - Instructions about arguments:

    | OPTIONS          | DESCRIPTIONS                                                     |
    |------------------+------------------------------------------------------------------|
    | -h               | for this list                                                    |
    | -o <op file>     | to specify operator file                                         |
    | -f <fact file>   | to specify fact file                                             |
    | -t <integer>     | to specify a fixed number of time steps                          |
    | -i <info level>  | to specify info level 1 or 2 (default is 0)                      |
    | -O <option list> | to specify options you want                                      |
    | -M <integer>     | to specify alternative max nodes in a time step (default is 256) |
    | -d               | give default values to everything not specified                  |
    
    Note: graphplan will prompt for '-t' and '-O' during execution
          
